#!/bin/bash

# The lnd v0.5.1 has other locations for wallet & macaroon files. Before it has these files not related with chain directory.
# This update unifies locations because some third-party utilities (ln-rebalance for examnple and lnwallet use standard paths)

set -e

LND_DIR=$HOME/.lnd

[[ -f $HOME/.testnet-lnd.pid ]] && kill -0 `cat $HOME/.testnet-lnd.pid` &>/dev/null && echo "You must to stop testnet lnd before update!" && exit 1
[[ -f $HOME/.mainnet-lnd.pid ]] && kill -0 `cat $HOME/.mainnet-lnd.pid` &>/dev/null && echo "You must to stop mainnet lnd before update!" && exit 2

if [[ `openssl x509 -in $LND_DIR/tls.cert -text -noout |grep 'lnd autogenerated cert'` == "" ]]; then
    # Need to update!
    rm -f $LND_DIR/tls.cert
    rm -f $LND_DIR/tls.key
fi
